SELECT
    T1.BUTTON_ID,
    T1.FUNCTION_ID,
    T1.BUTTON_NAME,
    T2.FUNCTION_NAME,
    T1.PAGE_TYPE
FROM
    PERMISSION.BUTTON T1
JOIN
    PERMISSION.FUNCTION T2
ON
    T1.FUNCTION_ID = T2.FUNCTION_ID
ORDER BY
    T1.BUTTON_ID ASC, T1.SEQ ASC