SELECT
    T1.LOCATION_ID,
    T1.LOCATION_NAME,
    T1.PM,
    T1.SALES,
    T1.WORKING_TIME,
    T1.OFF_TIME,
    T1.LUNCH_TIME
FROM
    HR.LOCATION T1
${CONDITIONS}
ORDER BY
    T1.LOCATION_ID ASC