SELECT
    T1.EMP_ID,
    T1.EMP_CNAME,
    T1.DEPARTMENT_ID,
    T3.DEPARTMENT_NAME,
    (
        SELECT
            T2.DISPLAY
        FROM
            BASE.PARAM T2
        WHERE
            T2.KEY = 'jobtitle'
        AND T2.VALUE = T1.JOBTITLE) AS JOBTITLE_NAME,
    T1.JOBTITLE,
    T1.GENDER,
    T1.EMPTYPE,
    T4.WORKING_TIME,
    T4.OFF_TIME,
    T4.LUNCH_TIME
FROM
    HR.EMPLOYEE T1
JOIN
    BASE.DEPARTMENT T3
ON
    T1.DEPARTMENT_ID = T3.DEPARTMENT_ID
LEFT JOIN
    HR.LOCATION T4
ON
    T1.LOCATION_ID = T4.LOCATION_ID 
${CONDITIONS}
ORDER BY
    T1.EMP_ID ASC