package com.elitech.human.resource.pojo;
// Generated Nov 15, 2017 6:10:17 PM by Hibernate Tools 4.0.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Button generated by hbm2java
 */
@Entity
@Table(name="button"
    ,schema="permission"
)
public class Button  implements java.io.Serializable {


     private String buttonId;
     private String buttonName;
     private String functionId;
     private String pageType;
     private long seq;
     private String action;
     private String createUser;
     private Date createTime;
     private String modifyUser;
     private Date modifyTime;
     private String buttonType;

    public Button() {
    }

	
    public Button(String buttonId, String buttonName, String functionId, String pageType, long seq, String action, String createUser, Date createTime) {
        this.buttonId = buttonId;
        this.buttonName = buttonName;
        this.functionId = functionId;
        this.pageType = pageType;
        this.seq = seq;
        this.action = action;
        this.createUser = createUser;
        this.createTime = createTime;
    }
    public Button(String buttonId, String buttonName, String functionId, String pageType, long seq, String action, String createUser, Date createTime, String modifyUser, Date modifyTime, String buttonType) {
       this.buttonId = buttonId;
       this.buttonName = buttonName;
       this.functionId = functionId;
       this.pageType = pageType;
       this.seq = seq;
       this.action = action;
       this.createUser = createUser;
       this.createTime = createTime;
       this.modifyUser = modifyUser;
       this.modifyTime = modifyTime;
       this.buttonType = buttonType;
    }
   
     @Id 

    
    @Column(name="button_id", unique=true, nullable=false, length=50)
    public String getButtonId() {
        return this.buttonId;
    }
    
    public void setButtonId(String buttonId) {
        this.buttonId = buttonId;
    }

    
    @Column(name="button_name", nullable=false, length=100)
    public String getButtonName() {
        return this.buttonName;
    }
    
    public void setButtonName(String buttonName) {
        this.buttonName = buttonName;
    }

    
    @Column(name="function_id", nullable=false, length=50)
    public String getFunctionId() {
        return this.functionId;
    }
    
    public void setFunctionId(String functionId) {
        this.functionId = functionId;
    }

    
    @Column(name="page_type", nullable=false)
    public String getPageType() {
        return this.pageType;
    }
    
    public void setPageType(String pageType) {
        this.pageType = pageType;
    }

    
    @Column(name="seq", nullable=false)
    public long getSeq() {
        return this.seq;
    }
    
    public void setSeq(long seq) {
        this.seq = seq;
    }

    
    @Column(name="action", nullable=false, length=50)
    public String getAction() {
        return this.action;
    }
    
    public void setAction(String action) {
        this.action = action;
    }

    
    @Column(name="create_user", nullable=false, length=20)
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_time", nullable=false, length=35)
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    
    @Column(name="modify_user", length=20)
    public String getModifyUser() {
        return this.modifyUser;
    }
    
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modify_time", length=35)
    public Date getModifyTime() {
        return this.modifyTime;
    }
    
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    
    @Column(name="button_type", length=7)
    public String getButtonType() {
        return this.buttonType;
    }
    
    public void setButtonType(String buttonType) {
        this.buttonType = buttonType;
    }




}


