package com.elitech.human.resource.pojo;
// Generated Dec 4, 2017 6:16:52 PM by Hibernate Tools 4.0.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name="employee"
    ,schema="hr"
)
public class Employee  implements java.io.Serializable {


     private String empId;
     private String email;
     private String companyEmail;
     private String empCname;
     private String empEname;
     private String gender;
     private Date birthday;
     private String marriage;
     private String served;
     private String emptype;
     private String departmentId;
     private String locationId;
     private String jobstatus;
     private String jobtitle;
     private Date onBoard;
     private String education;
     private String schoolename;
     private String subject;
     private String tel;
     private String phone;
     private String zipcode;
     private String address;
     private String emergencycontact;
     private String emergencytel;
     private String createUser;
     private Date createTime;
     private String modifyUser;
     private Date modifyTime;

    public Employee() {
    }

	
    public Employee(String empId, String email, String companyEmail, String empCname, String gender, Date birthday, String marriage, String served, String emptype, String locationId, Date onBoard, String createUser, Date createTime) {
        this.empId = empId;
        this.email = email;
        this.companyEmail = companyEmail;
        this.empCname = empCname;
        this.gender = gender;
        this.birthday = birthday;
        this.marriage = marriage;
        this.served = served;
        this.emptype = emptype;
        this.locationId = locationId;
        this.onBoard = onBoard;
        this.createUser = createUser;
        this.createTime = createTime;
    }
    public Employee(String empId, String email, String companyEmail, String empCname, String empEname, String gender, Date birthday, String marriage, String served, String emptype, String departmentId, String locationId, String jobstatus, String jobtitle, Date onBoard, String education, String schoolename, String subject, String tel, String phone, String zipcode, String address, String emergencycontact, String emergencytel, String createUser, Date createTime, String modifyUser, Date modifyTime) {
       this.empId = empId;
       this.email = email;
       this.companyEmail = companyEmail;
       this.empCname = empCname;
       this.empEname = empEname;
       this.gender = gender;
       this.birthday = birthday;
       this.marriage = marriage;
       this.served = served;
       this.emptype = emptype;
       this.departmentId = departmentId;
       this.locationId = locationId;
       this.jobstatus = jobstatus;
       this.jobtitle = jobtitle;
       this.onBoard = onBoard;
       this.education = education;
       this.schoolename = schoolename;
       this.subject = subject;
       this.tel = tel;
       this.phone = phone;
       this.zipcode = zipcode;
       this.address = address;
       this.emergencycontact = emergencycontact;
       this.emergencytel = emergencytel;
       this.createUser = createUser;
       this.createTime = createTime;
       this.modifyUser = modifyUser;
       this.modifyTime = modifyTime;
    }
   
     @Id 

    
    @Column(name="emp_id", unique=true, nullable=false, length=20)
    public String getEmpId() {
        return this.empId;
    }
    
    public void setEmpId(String empId) {
        this.empId = empId;
    }

    
    @Column(name="email", nullable=false, length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="company_email", nullable=false, length=100)
    public String getCompanyEmail() {
        return this.companyEmail;
    }
    
    public void setCompanyEmail(String companyEmail) {
        this.companyEmail = companyEmail;
    }

    
    @Column(name="emp_cname", nullable=false, length=50)
    public String getEmpCname() {
        return this.empCname;
    }
    
    public void setEmpCname(String empCname) {
        this.empCname = empCname;
    }

    
    @Column(name="emp_ename", length=50)
    public String getEmpEname() {
        return this.empEname;
    }
    
    public void setEmpEname(String empEname) {
        this.empEname = empEname;
    }

    
    @Column(name="gender", nullable=false, length=1)
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="birthday", nullable=false, length=13)
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    
    @Column(name="marriage", nullable=false, length=1)
    public String getMarriage() {
        return this.marriage;
    }
    
    public void setMarriage(String marriage) {
        this.marriage = marriage;
    }

    
    @Column(name="served", nullable=false, length=1)
    public String getServed() {
        return this.served;
    }
    
    public void setServed(String served) {
        this.served = served;
    }

    
    @Column(name="emptype", nullable=false, length=1)
    public String getEmptype() {
        return this.emptype;
    }
    
    public void setEmptype(String emptype) {
        this.emptype = emptype;
    }

    
    @Column(name="department_id", length=5)
    public String getDepartmentId() {
        return this.departmentId;
    }
    
    public void setDepartmentId(String departmentId) {
        this.departmentId = departmentId;
    }

    
    @Column(name="location_id", nullable=false, length=20)
    public String getLocationId() {
        return this.locationId;
    }
    
    public void setLocationId(String locationId) {
        this.locationId = locationId;
    }

    
    @Column(name="jobstatus", length=1)
    public String getJobstatus() {
        return this.jobstatus;
    }
    
    public void setJobstatus(String jobstatus) {
        this.jobstatus = jobstatus;
    }

    
    @Column(name="jobtitle", length=4)
    public String getJobtitle() {
        return this.jobtitle;
    }
    
    public void setJobtitle(String jobtitle) {
        this.jobtitle = jobtitle;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="on_board", nullable=false, length=13)
    public Date getOnBoard() {
        return this.onBoard;
    }
    
    public void setOnBoard(Date onBoard) {
        this.onBoard = onBoard;
    }

    
    @Column(name="education", length=1)
    public String getEducation() {
        return this.education;
    }
    
    public void setEducation(String education) {
        this.education = education;
    }

    
    @Column(name="schoolename", length=100)
    public String getSchoolename() {
        return this.schoolename;
    }
    
    public void setSchoolename(String schoolename) {
        this.schoolename = schoolename;
    }

    
    @Column(name="subject", length=50)
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }

    
    @Column(name="tel", length=20)
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }

    
    @Column(name="phone", length=10)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="zipcode", length=5)
    public String getZipcode() {
        return this.zipcode;
    }
    
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode;
    }

    
    @Column(name="address", length=100)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="emergencycontact", length=50)
    public String getEmergencycontact() {
        return this.emergencycontact;
    }
    
    public void setEmergencycontact(String emergencycontact) {
        this.emergencycontact = emergencycontact;
    }

    
    @Column(name="emergencytel", length=50)
    public String getEmergencytel() {
        return this.emergencytel;
    }
    
    public void setEmergencytel(String emergencytel) {
        this.emergencytel = emergencytel;
    }

    
    @Column(name="create_user", nullable=false, length=20)
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_time", nullable=false, length=35)
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    
    @Column(name="modify_user", length=20)
    public String getModifyUser() {
        return this.modifyUser;
    }
    
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modify_time", length=35)
    public Date getModifyTime() {
        return this.modifyTime;
    }
    
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }




}


