package com.elitech.human.resource.pojo;
// Generated Nov 6, 2017 5:40:29 PM by Hibernate Tools 4.0.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Function generated by hbm2java
 */
@Entity
@Table(name="function"
    ,schema="permission"
)
public class Function  implements java.io.Serializable {


     private String functionId;
     private String functionName;
     private String menuId;
     private String status;
     private String namespace;
     private long seq;
     private String createUser;
     private Date createTime;
     private String modifyUser;
     private Date modifyTime;

    public Function() {
    }

	
    public Function(String functionId, String functionName, String status, String namespace, long seq, String createUser, Date createTime) {
        this.functionId = functionId;
        this.functionName = functionName;
        this.status = status;
        this.namespace = namespace;
        this.seq = seq;
        this.createUser = createUser;
        this.createTime = createTime;
    }
    public Function(String functionId, String functionName, String menuId, String status, String namespace, long seq, String createUser, Date createTime, String modifyUser, Date modifyTime) {
       this.functionId = functionId;
       this.functionName = functionName;
       this.menuId = menuId;
       this.status = status;
       this.namespace = namespace;
       this.seq = seq;
       this.createUser = createUser;
       this.createTime = createTime;
       this.modifyUser = modifyUser;
       this.modifyTime = modifyTime;
    }
   
     @Id 

    
    @Column(name="function_id", unique=true, nullable=false, length=50)
    public String getFunctionId() {
        return this.functionId;
    }
    
    public void setFunctionId(String functionId) {
        this.functionId = functionId;
    }

    
    @Column(name="function_name", nullable=false, length=100)
    public String getFunctionName() {
        return this.functionName;
    }
    
    public void setFunctionName(String functionName) {
        this.functionName = functionName;
    }

    
    @Column(name="menu_id", length=50)
    public String getMenuId() {
        return this.menuId;
    }
    
    public void setMenuId(String menuId) {
        this.menuId = menuId;
    }

    
    @Column(name="status", nullable=false, length=1)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="namespace", nullable=false)
    public String getNamespace() {
        return this.namespace;
    }
    
    public void setNamespace(String namespace) {
        this.namespace = namespace;
    }

    
    @Column(name="seq", nullable=false)
    public long getSeq() {
        return this.seq;
    }
    
    public void setSeq(long seq) {
        this.seq = seq;
    }

    
    @Column(name="create_user", nullable=false, length=20)
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_time", nullable=false, length=35)
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    
    @Column(name="modify_user", length=20)
    public String getModifyUser() {
        return this.modifyUser;
    }
    
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modify_time", length=35)
    public Date getModifyTime() {
        return this.modifyTime;
    }
    
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }




}


