package com.elitech.human.resource.pojo;
// Generated Dec 6, 2017 2:17:34 PM by Hibernate Tools 4.0.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LeaveSetting generated by hbm2java
 */
@Entity
@Table(name="leave_setting"
    ,schema="hr"
)
public class LeaveSetting  implements java.io.Serializable {


     private long seq;
     private String emptype;
     private String leavetypeId;
     private String leaveYear;
     private double years;
     private long leaveDays;
     private String isProportional;
     private String createUser;
     private Date createTime;
     private String modifyUser;
     private Date modifyTime;

    public LeaveSetting() {
    }

	
    public LeaveSetting(long seq, String emptype, String leavetypeId, String leaveYear, double years, long leaveDays, String isProportional, String createUser, Date createTime) {
        this.seq = seq;
        this.emptype = emptype;
        this.leavetypeId = leavetypeId;
        this.leaveYear = leaveYear;
        this.years = years;
        this.leaveDays = leaveDays;
        this.isProportional = isProportional;
        this.createUser = createUser;
        this.createTime = createTime;
    }
    public LeaveSetting(long seq, String emptype, String leavetypeId, String leaveYear, double years, long leaveDays, String isProportional, String createUser, Date createTime, String modifyUser, Date modifyTime) {
       this.seq = seq;
       this.emptype = emptype;
       this.leavetypeId = leavetypeId;
       this.leaveYear = leaveYear;
       this.years = years;
       this.leaveDays = leaveDays;
       this.isProportional = isProportional;
       this.createUser = createUser;
       this.createTime = createTime;
       this.modifyUser = modifyUser;
       this.modifyTime = modifyTime;
    }
   
     @Id 

    
    @Column(name="seq", unique=true, nullable=false)
    public long getSeq() {
        return this.seq;
    }
    
    public void setSeq(long seq) {
        this.seq = seq;
    }

    
    @Column(name="emptype", nullable=false, length=1)
    public String getEmptype() {
        return this.emptype;
    }
    
    public void setEmptype(String emptype) {
        this.emptype = emptype;
    }

    
    @Column(name="leavetype_id", nullable=false, length=6)
    public String getLeavetypeId() {
        return this.leavetypeId;
    }
    
    public void setLeavetypeId(String leavetypeId) {
        this.leavetypeId = leavetypeId;
    }

    
    @Column(name="leave_year", nullable=false, length=4)
    public String getLeaveYear() {
        return this.leaveYear;
    }
    
    public void setLeaveYear(String leaveYear) {
        this.leaveYear = leaveYear;
    }

    
    @Column(name="years", nullable=false, precision=17, scale=17)
    public double getYears() {
        return this.years;
    }
    
    public void setYears(double years) {
        this.years = years;
    }

    
    @Column(name="leave_days", nullable=false)
    public long getLeaveDays() {
        return this.leaveDays;
    }
    
    public void setLeaveDays(long leaveDays) {
        this.leaveDays = leaveDays;
    }

    
    @Column(name="is_proportional", nullable=false, length=1)
    public String getIsProportional() {
        return this.isProportional;
    }
    
    public void setIsProportional(String isProportional) {
        this.isProportional = isProportional;
    }

    
    @Column(name="create_user", nullable=false, length=20)
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_time", nullable=false, length=35)
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    
    @Column(name="modify_user", length=20)
    public String getModifyUser() {
        return this.modifyUser;
    }
    
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modify_time", length=35)
    public Date getModifyTime() {
        return this.modifyTime;
    }
    
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }




}


