package com.elitech.human.resource.pojo;
// Generated Dec 20, 2017 4:49:16 PM by Hibernate Tools 4.0.0


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Leavetype generated by hbm2java
 */
@Entity
@Table(name="leavetype"
    ,schema="base"
)
public class Leavetype  implements java.io.Serializable {


     private LeavetypeId id;
     private String leaveName;
     private String unit;
     private String gender;
     private Long expire;
     private String isYears;
     private String isSubstitute;
     private String isDocument;
     private String documentMsg;
     private String status;
     private String createUser;
     private Date createTime;
     private String modifyUser;
     private Date modifyTime;

    public Leavetype() {
    }

	
    public Leavetype(LeavetypeId id, String leaveName, String unit, String isYears, String isSubstitute, String isDocument, String status, String createUser, Date createTime) {
        this.id = id;
        this.leaveName = leaveName;
        this.unit = unit;
        this.isYears = isYears;
        this.isSubstitute = isSubstitute;
        this.isDocument = isDocument;
        this.status = status;
        this.createUser = createUser;
        this.createTime = createTime;
    }
    public Leavetype(LeavetypeId id, String leaveName, String unit, String gender, Long expire, String isYears, String isSubstitute, String isDocument, String documentMsg, String status, String createUser, Date createTime, String modifyUser, Date modifyTime) {
       this.id = id;
       this.leaveName = leaveName;
       this.unit = unit;
       this.gender = gender;
       this.expire = expire;
       this.isYears = isYears;
       this.isSubstitute = isSubstitute;
       this.isDocument = isDocument;
       this.documentMsg = documentMsg;
       this.status = status;
       this.createUser = createUser;
       this.createTime = createTime;
       this.modifyUser = modifyUser;
       this.modifyTime = modifyTime;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="leavetypeId", column=@Column(name="leavetype_id", nullable=false, length=6) ), 
        @AttributeOverride(name="emptype", column=@Column(name="emptype", nullable=false, length=1) ) } )
    public LeavetypeId getId() {
        return this.id;
    }
    
    public void setId(LeavetypeId id) {
        this.id = id;
    }

    
    @Column(name="leave_name", nullable=false, length=50)
    public String getLeaveName() {
        return this.leaveName;
    }
    
    public void setLeaveName(String leaveName) {
        this.leaveName = leaveName;
    }

    
    @Column(name="unit", nullable=false, length=1)
    public String getUnit() {
        return this.unit;
    }
    
    public void setUnit(String unit) {
        this.unit = unit;
    }

    
    @Column(name="gender")
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }

    
    @Column(name="expire")
    public Long getExpire() {
        return this.expire;
    }
    
    public void setExpire(Long expire) {
        this.expire = expire;
    }

    
    @Column(name="is_years", nullable=false, length=1)
    public String getIsYears() {
        return this.isYears;
    }
    
    public void setIsYears(String isYears) {
        this.isYears = isYears;
    }

    
    @Column(name="is_substitute", nullable=false, length=1)
    public String getIsSubstitute() {
        return this.isSubstitute;
    }
    
    public void setIsSubstitute(String isSubstitute) {
        this.isSubstitute = isSubstitute;
    }

    
    @Column(name="is_document", nullable=false, length=1)
    public String getIsDocument() {
        return this.isDocument;
    }
    
    public void setIsDocument(String isDocument) {
        this.isDocument = isDocument;
    }

    
    @Column(name="document_msg", length=50)
    public String getDocumentMsg() {
        return this.documentMsg;
    }
    
    public void setDocumentMsg(String documentMsg) {
        this.documentMsg = documentMsg;
    }

    
    @Column(name="status", nullable=false, length=1)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="create_user", nullable=false, length=20)
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_time", nullable=false, length=35)
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    
    @Column(name="modify_user", length=20)
    public String getModifyUser() {
        return this.modifyUser;
    }
    
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modify_time", length=35)
    public Date getModifyTime() {
        return this.modifyTime;
    }
    
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }




}


