package com.elitech.human.resource.pojo;
// Generated Dec 20, 2017 4:49:16 PM by Hibernate Tools 4.0.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LeavetypeId generated by hbm2java
 */
@Embeddable
public class LeavetypeId  implements java.io.Serializable {


     private String leavetypeId;
     private String emptype;

    public LeavetypeId() {
    }

    public LeavetypeId(String leavetypeId, String emptype) {
       this.leavetypeId = leavetypeId;
       this.emptype = emptype;
    }
   


    @Column(name="leavetype_id", nullable=false, length=6)
    public String getLeavetypeId() {
        return this.leavetypeId;
    }
    
    public void setLeavetypeId(String leavetypeId) {
        this.leavetypeId = leavetypeId;
    }


    @Column(name="emptype", nullable=false, length=1)
    public String getEmptype() {
        return this.emptype;
    }
    
    public void setEmptype(String emptype) {
        this.emptype = emptype;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LeavetypeId) ) return false;
		 LeavetypeId castOther = ( LeavetypeId ) other; 
         
		 return ( (this.getLeavetypeId()==castOther.getLeavetypeId()) || ( this.getLeavetypeId()!=null && castOther.getLeavetypeId()!=null && this.getLeavetypeId().equals(castOther.getLeavetypeId()) ) )
 && ( (this.getEmptype()==castOther.getEmptype()) || ( this.getEmptype()!=null && castOther.getEmptype()!=null && this.getEmptype().equals(castOther.getEmptype()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getLeavetypeId() == null ? 0 : this.getLeavetypeId().hashCode() );
         result = 37 * result + ( getEmptype() == null ? 0 : this.getEmptype().hashCode() );
         return result;
   }   


}


