package com.elitech.human.resource.pojo;
// Generated Jan 15, 2018 11:20:40 AM by Hibernate Tools 4.0.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LeavedayD generated by hbm2java
 */
@Entity
@Table(name="leaveday_d"
    ,schema="hr"
)
public class LeavedayD  implements java.io.Serializable {


     private long seq;
     private String empId;
     private long years;
     private Date transDate;
     private String leavetypeId;
     private String action;
     private double hours;
     private String createUser;
     private Date createTime;
     private String modifyUser;
     private Date modifyTime;
     private String leaveNo;
     private String note;

    public LeavedayD() {
    }

	
    public LeavedayD(long seq, String empId, long years, Date transDate, String leavetypeId, String action, double hours, String createUser, Date createTime) {
        this.seq = seq;
        this.empId = empId;
        this.years = years;
        this.transDate = transDate;
        this.leavetypeId = leavetypeId;
        this.action = action;
        this.hours = hours;
        this.createUser = createUser;
        this.createTime = createTime;
    }
    public LeavedayD(long seq, String empId, long years, Date transDate, String leavetypeId, String action, double hours, String createUser, Date createTime, String modifyUser, Date modifyTime, String leaveNo, String note) {
       this.seq = seq;
       this.empId = empId;
       this.years = years;
       this.transDate = transDate;
       this.leavetypeId = leavetypeId;
       this.action = action;
       this.hours = hours;
       this.createUser = createUser;
       this.createTime = createTime;
       this.modifyUser = modifyUser;
       this.modifyTime = modifyTime;
       this.leaveNo = leaveNo;
       this.note = note;
    }
   
     @Id 

    
    @Column(name="seq", unique=true, nullable=false)
    public long getSeq() {
        return this.seq;
    }
    
    public void setSeq(long seq) {
        this.seq = seq;
    }

    
    @Column(name="emp_id", nullable=false, length=20)
    public String getEmpId() {
        return this.empId;
    }
    
    public void setEmpId(String empId) {
        this.empId = empId;
    }

    
    @Column(name="years", nullable=false)
    public long getYears() {
        return this.years;
    }
    
    public void setYears(long years) {
        this.years = years;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="trans_date", nullable=false, length=13)
    public Date getTransDate() {
        return this.transDate;
    }
    
    public void setTransDate(Date transDate) {
        this.transDate = transDate;
    }

    
    @Column(name="leavetype_id", nullable=false, length=6)
    public String getLeavetypeId() {
        return this.leavetypeId;
    }
    
    public void setLeavetypeId(String leavetypeId) {
        this.leavetypeId = leavetypeId;
    }

    
    @Column(name="action", nullable=false, length=1)
    public String getAction() {
        return this.action;
    }
    
    public void setAction(String action) {
        this.action = action;
    }

    
    @Column(name="hours", nullable=false, precision=17, scale=17)
    public double getHours() {
        return this.hours;
    }
    
    public void setHours(double hours) {
        this.hours = hours;
    }

    
    @Column(name="create_user", nullable=false, length=20)
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_time", nullable=false, length=35)
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    
    @Column(name="modify_user", length=20)
    public String getModifyUser() {
        return this.modifyUser;
    }
    
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modify_time", length=35)
    public Date getModifyTime() {
        return this.modifyTime;
    }
    
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    
    @Column(name="leave_no", length=12)
    public String getLeaveNo() {
        return this.leaveNo;
    }
    
    public void setLeaveNo(String leaveNo) {
        this.leaveNo = leaveNo;
    }

    
    @Column(name="note")
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }




}


