package com.elitech.human.resource.pojo;
// Generated Jan 15, 2018 4:40:01 PM by Hibernate Tools 4.0.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Location generated by hbm2java
 */
@Entity
@Table(name="location"
    ,schema="hr"
)
public class Location  implements java.io.Serializable {


     private String locationId;
     private String locationName;
     private String pm;
     private String sales;
     private String workingTime;
     private String offTime;
     private double lunchTime;
     private String createUser;
     private Date createTime;
     private String modifyUser;
     private Date modifyTime;

    public Location() {
    }

	
    public Location(String locationId, String locationName, String sales, String workingTime, String offTime, double lunchTime, String createUser, Date createTime) {
        this.locationId = locationId;
        this.locationName = locationName;
        this.sales = sales;
        this.workingTime = workingTime;
        this.offTime = offTime;
        this.lunchTime = lunchTime;
        this.createUser = createUser;
        this.createTime = createTime;
    }
    public Location(String locationId, String locationName, String pm, String sales, String workingTime, String offTime, double lunchTime, String createUser, Date createTime, String modifyUser, Date modifyTime) {
       this.locationId = locationId;
       this.locationName = locationName;
       this.pm = pm;
       this.sales = sales;
       this.workingTime = workingTime;
       this.offTime = offTime;
       this.lunchTime = lunchTime;
       this.createUser = createUser;
       this.createTime = createTime;
       this.modifyUser = modifyUser;
       this.modifyTime = modifyTime;
    }
   
     @Id 

    
    @Column(name="location_id", unique=true, nullable=false, length=20)
    public String getLocationId() {
        return this.locationId;
    }
    
    public void setLocationId(String locationId) {
        this.locationId = locationId;
    }

    
    @Column(name="location_name", nullable=false, length=50)
    public String getLocationName() {
        return this.locationName;
    }
    
    public void setLocationName(String locationName) {
        this.locationName = locationName;
    }

    
    @Column(name="pm", length=20)
    public String getPm() {
        return this.pm;
    }
    
    public void setPm(String pm) {
        this.pm = pm;
    }

    
    @Column(name="sales", nullable=false, length=20)
    public String getSales() {
        return this.sales;
    }
    
    public void setSales(String sales) {
        this.sales = sales;
    }

    
    @Column(name="working_time", nullable=false, length=4)
    public String getWorkingTime() {
        return this.workingTime;
    }
    
    public void setWorkingTime(String workingTime) {
        this.workingTime = workingTime;
    }

    
    @Column(name="off_time", nullable=false, length=4)
    public String getOffTime() {
        return this.offTime;
    }
    
    public void setOffTime(String offTime) {
        this.offTime = offTime;
    }

    
    @Column(name="lunch_time", nullable=false, precision=17, scale=17)
    public double getLunchTime() {
        return this.lunchTime;
    }
    
    public void setLunchTime(double lunchTime) {
        this.lunchTime = lunchTime;
    }

    
    @Column(name="create_user", nullable=false, length=20)
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_time", nullable=false, length=35)
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    
    @Column(name="modify_user", length=20)
    public String getModifyUser() {
        return this.modifyUser;
    }
    
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modify_time", length=35)
    public Date getModifyTime() {
        return this.modifyTime;
    }
    
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }




}


