package com.elitech.human.resource.pojo;
// Generated Dec 26, 2017 2:26:51 PM by Hibernate Tools 4.0.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LoginUser generated by hbm2java
 */
@Entity
@Table(name="login_user"
    ,schema="permission"
)
public class LoginUser  implements java.io.Serializable {


     private String userId;
     private String userName;
     private String email;
     private String status;
     private String createUser;
     private Date createTime;
     private String modifyUser;
     private Date modifyTime;

    public LoginUser() {
    }

	
    public LoginUser(String userId, String userName, String email, String status, String createUser, Date createTime) {
        this.userId = userId;
        this.userName = userName;
        this.email = email;
        this.status = status;
        this.createUser = createUser;
        this.createTime = createTime;
    }
    public LoginUser(String userId, String userName, String email, String status, String createUser, Date createTime, String modifyUser, Date modifyTime) {
       this.userId = userId;
       this.userName = userName;
       this.email = email;
       this.status = status;
       this.createUser = createUser;
       this.createTime = createTime;
       this.modifyUser = modifyUser;
       this.modifyTime = modifyTime;
    }
   
     @Id 

    
    @Column(name="user_id", unique=true, nullable=false, length=20)
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }

    
    @Column(name="user_name", nullable=false, length=100)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    
    @Column(name="email", nullable=false, length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="status", nullable=false, length=1)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="create_user", nullable=false, length=20)
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_time", nullable=false, length=35)
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    
    @Column(name="modify_user", length=20)
    public String getModifyUser() {
        return this.modifyUser;
    }
    
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modify_time", length=35)
    public Date getModifyTime() {
        return this.modifyTime;
    }
    
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }




}


