package com.elitech.human.resource.pojo;
// Generated Nov 10, 2017 3:47:26 PM by Hibernate Tools 4.0.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Menu generated by hbm2java
 */
@Entity
@Table(name="menu"
    ,schema="permission"
)
public class Menu  implements java.io.Serializable {


     private String menuId;
     private String menuName;
     private String PMenuId;
     private String status;
     private Long seq;
     private String createUser;
     private Date createTime;
     private String modifyUser;
     private Date modifyTime;
     private String icon;

    public Menu() {
    }

	
    public Menu(String menuId, String menuName, String status, String createUser, Date createTime) {
        this.menuId = menuId;
        this.menuName = menuName;
        this.status = status;
        this.createUser = createUser;
        this.createTime = createTime;
    }
    public Menu(String menuId, String menuName, String PMenuId, String status, Long seq, String createUser, Date createTime, String modifyUser, Date modifyTime, String icon) {
       this.menuId = menuId;
       this.menuName = menuName;
       this.PMenuId = PMenuId;
       this.status = status;
       this.seq = seq;
       this.createUser = createUser;
       this.createTime = createTime;
       this.modifyUser = modifyUser;
       this.modifyTime = modifyTime;
       this.icon = icon;
    }
   
     @Id 

    
    @Column(name="menu_id", unique=true, nullable=false, length=50)
    public String getMenuId() {
        return this.menuId;
    }
    
    public void setMenuId(String menuId) {
        this.menuId = menuId;
    }

    
    @Column(name="menu_name", nullable=false, length=100)
    public String getMenuName() {
        return this.menuName;
    }
    
    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }

    
    @Column(name="p_menu_id")
    public String getPMenuId() {
        return this.PMenuId;
    }
    
    public void setPMenuId(String PMenuId) {
        this.PMenuId = PMenuId;
    }

    
    @Column(name="status", nullable=false, length=1)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="seq")
    public Long getSeq() {
        return this.seq;
    }
    
    public void setSeq(Long seq) {
        this.seq = seq;
    }

    
    @Column(name="create_user", nullable=false, length=20)
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_time", nullable=false, length=35)
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    
    @Column(name="modify_user", length=20)
    public String getModifyUser() {
        return this.modifyUser;
    }
    
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modify_time", length=35)
    public Date getModifyTime() {
        return this.modifyTime;
    }
    
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    
    @Column(name="icon", length=20)
    public String getIcon() {
        return this.icon;
    }
    
    public void setIcon(String icon) {
        this.icon = icon;
    }




}


