package com.elitech.human.resource.pojo;
// Generated Nov 28, 2017 10:45:08 AM by Hibernate Tools 4.0.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ParamId generated by hbm2java
 */
@Embeddable
public class ParamId  implements java.io.Serializable {


     private String key;
     private String value;

    public ParamId() {
    }

    public ParamId(String key, String value) {
       this.key = key;
       this.value = value;
    }
   


    @Column(name="key", nullable=false, length=20)
    public String getKey() {
        return this.key;
    }
    
    public void setKey(String key) {
        this.key = key;
    }


    @Column(name="value", nullable=false, length=50)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ParamId) ) return false;
		 ParamId castOther = ( ParamId ) other; 
         
		 return ( (this.getKey()==castOther.getKey()) || ( this.getKey()!=null && castOther.getKey()!=null && this.getKey().equals(castOther.getKey()) ) )
 && ( (this.getValue()==castOther.getValue()) || ( this.getValue()!=null && castOther.getValue()!=null && this.getValue().equals(castOther.getValue()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getKey() == null ? 0 : this.getKey().hashCode() );
         result = 37 * result + ( getValue() == null ? 0 : this.getValue().hashCode() );
         return result;
   }   


}


