package com.elitech.human.resource.pojo;
// Generated Nov 28, 2017 10:45:08 AM by Hibernate Tools 4.0.0


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Param generated by hbm2java
 */
@Entity
@Table(name="param"
    ,schema="base"
)
public class Param  implements java.io.Serializable {


     private ParamId id;
     private String status;
     private String display;
     private Long seq;

    public Param() {
    }

	
    public Param(ParamId id, String status, String display) {
        this.id = id;
        this.status = status;
        this.display = display;
    }
    public Param(ParamId id, String status, String display, Long seq) {
       this.id = id;
       this.status = status;
       this.display = display;
       this.seq = seq;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="key", column=@Column(name="key", nullable=false, length=20) ), 
        @AttributeOverride(name="value", column=@Column(name="value", nullable=false, length=50) ) } )
    public ParamId getId() {
        return this.id;
    }
    
    public void setId(ParamId id) {
        this.id = id;
    }

    
    @Column(name="status", nullable=false, length=1)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="display", nullable=false, length=100)
    public String getDisplay() {
        return this.display;
    }
    
    public void setDisplay(String display) {
        this.display = display;
    }

    
    @Column(name="seq")
    public Long getSeq() {
        return this.seq;
    }
    
    public void setSeq(Long seq) {
        this.seq = seq;
    }




}


