package com.elitech.human.resource.pojo;
// Generated Nov 6, 2017 5:40:29 PM by Hibernate Tools 4.0.0


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PermissionUser generated by hbm2java
 */
@Entity
@Table(name="permission_user"
    ,schema="permission"
)
public class PermissionUser  implements java.io.Serializable {


     private PermissionUserId id;
     private String createUser;
     private Date createTime;
     private String modifyUser;
     private Date modifyTime;

    public PermissionUser() {
    }

	
    public PermissionUser(PermissionUserId id, String createUser, Date createTime) {
        this.id = id;
        this.createUser = createUser;
        this.createTime = createTime;
    }
    public PermissionUser(PermissionUserId id, String createUser, Date createTime, String modifyUser, Date modifyTime) {
       this.id = id;
       this.createUser = createUser;
       this.createTime = createTime;
       this.modifyUser = modifyUser;
       this.modifyTime = modifyTime;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="userId", column=@Column(name="user_id", nullable=false, length=20) ), 
        @AttributeOverride(name="functionId", column=@Column(name="function_id", nullable=false, length=50) ), 
        @AttributeOverride(name="buttonId", column=@Column(name="button_id", nullable=false, length=50) ) } )
    public PermissionUserId getId() {
        return this.id;
    }
    
    public void setId(PermissionUserId id) {
        this.id = id;
    }

    
    @Column(name="create_user", nullable=false, length=20)
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_time", nullable=false, length=35)
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    
    @Column(name="modify_user", length=20)
    public String getModifyUser() {
        return this.modifyUser;
    }
    
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modify_time", length=35)
    public Date getModifyTime() {
        return this.modifyTime;
    }
    
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }




}


