package com.elitech.human.resource.pojo;
// Generated Nov 6, 2017 5:40:29 PM by Hibernate Tools 4.0.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PermissionUserId generated by hbm2java
 */
@Embeddable
public class PermissionUserId  implements java.io.Serializable {


     private String userId;
     private String functionId;
     private String buttonId;

    public PermissionUserId() {
    }

    public PermissionUserId(String userId, String functionId, String buttonId) {
       this.userId = userId;
       this.functionId = functionId;
       this.buttonId = buttonId;
    }
   


    @Column(name="user_id", nullable=false, length=20)
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }


    @Column(name="function_id", nullable=false, length=50)
    public String getFunctionId() {
        return this.functionId;
    }
    
    public void setFunctionId(String functionId) {
        this.functionId = functionId;
    }


    @Column(name="button_id", nullable=false, length=50)
    public String getButtonId() {
        return this.buttonId;
    }
    
    public void setButtonId(String buttonId) {
        this.buttonId = buttonId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PermissionUserId) ) return false;
		 PermissionUserId castOther = ( PermissionUserId ) other; 
         
		 return ( (this.getUserId()==castOther.getUserId()) || ( this.getUserId()!=null && castOther.getUserId()!=null && this.getUserId().equals(castOther.getUserId()) ) )
 && ( (this.getFunctionId()==castOther.getFunctionId()) || ( this.getFunctionId()!=null && castOther.getFunctionId()!=null && this.getFunctionId().equals(castOther.getFunctionId()) ) )
 && ( (this.getButtonId()==castOther.getButtonId()) || ( this.getButtonId()!=null && castOther.getButtonId()!=null && this.getButtonId().equals(castOther.getButtonId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUserId() == null ? 0 : this.getUserId().hashCode() );
         result = 37 * result + ( getFunctionId() == null ? 0 : this.getFunctionId().hashCode() );
         result = 37 * result + ( getButtonId() == null ? 0 : this.getButtonId().hashCode() );
         return result;
   }   


}


