package com.elitech.human.resource.pojo;
// Generated Dec 19, 2017 4:19:29 PM by Hibernate Tools 4.0.0


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProcessFlow generated by hbm2java
 */
@Entity
@Table(name="process_flow"
    ,schema="hr"
)
public class ProcessFlow  implements java.io.Serializable {


     private ProcessFlowId id;
     private Date transDate;
     private String approveStatus;
     private String notes;

    public ProcessFlow() {
    }

	
    public ProcessFlow(ProcessFlowId id, Date transDate, String approveStatus) {
        this.id = id;
        this.transDate = transDate;
        this.approveStatus = approveStatus;
    }
    public ProcessFlow(ProcessFlowId id, Date transDate, String approveStatus, String notes) {
       this.id = id;
       this.transDate = transDate;
       this.approveStatus = approveStatus;
       this.notes = notes;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="empId", column=@Column(name="emp_id", nullable=false, length=20) ), 
        @AttributeOverride(name="leaveNo", column=@Column(name="leave_no", nullable=false, length=12) ), 
        @AttributeOverride(name="seq", column=@Column(name="seq", nullable=false) ) } )
    public ProcessFlowId getId() {
        return this.id;
    }
    
    public void setId(ProcessFlowId id) {
        this.id = id;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="trans_date", nullable=false, length=35)
    public Date getTransDate() {
        return this.transDate;
    }
    
    public void setTransDate(Date transDate) {
        this.transDate = transDate;
    }

    
    @Column(name="approve_status", nullable=false, length=10)
    public String getApproveStatus() {
        return this.approveStatus;
    }
    
    public void setApproveStatus(String approveStatus) {
        this.approveStatus = approveStatus;
    }

    
    @Column(name="notes", length=100)
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }




}


