package com.elitech.human.resource.pojo;
// Generated Dec 19, 2017 4:19:29 PM by Hibernate Tools 4.0.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProcessFlowId generated by hbm2java
 */
@Embeddable
public class ProcessFlowId  implements java.io.Serializable {


     private String empId;
     private String leaveNo;
     private long seq;

    public ProcessFlowId() {
    }

    public ProcessFlowId(String empId, String leaveNo, long seq) {
       this.empId = empId;
       this.leaveNo = leaveNo;
       this.seq = seq;
    }
   


    @Column(name="emp_id", nullable=false, length=20)
    public String getEmpId() {
        return this.empId;
    }
    
    public void setEmpId(String empId) {
        this.empId = empId;
    }


    @Column(name="leave_no", nullable=false, length=12)
    public String getLeaveNo() {
        return this.leaveNo;
    }
    
    public void setLeaveNo(String leaveNo) {
        this.leaveNo = leaveNo;
    }


    @Column(name="seq", nullable=false)
    public long getSeq() {
        return this.seq;
    }
    
    public void setSeq(long seq) {
        this.seq = seq;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProcessFlowId) ) return false;
		 ProcessFlowId castOther = ( ProcessFlowId ) other; 
         
		 return ( (this.getEmpId()==castOther.getEmpId()) || ( this.getEmpId()!=null && castOther.getEmpId()!=null && this.getEmpId().equals(castOther.getEmpId()) ) )
 && ( (this.getLeaveNo()==castOther.getLeaveNo()) || ( this.getLeaveNo()!=null && castOther.getLeaveNo()!=null && this.getLeaveNo().equals(castOther.getLeaveNo()) ) )
 && (this.getSeq()==castOther.getSeq());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getEmpId() == null ? 0 : this.getEmpId().hashCode() );
         result = 37 * result + ( getLeaveNo() == null ? 0 : this.getLeaveNo().hashCode() );
         result = 37 * result + (int) this.getSeq();
         return result;
   }   


}


