SELECT
    T1.LEAVE_NO,
    T1.EMP_ID,
    T1.LEAVETYPE_ID,
    T2.LEAVE_NAME,
    T1.CREATE_TIME,
    T1.BEGINDATE,
    T1.ENDDATE,
    T1.BEGINHOUR,
    T1.ENDHOUR,
    T1.BEGINMIN,
    T1.ENDMIN,
    T1.APPROVE_STATUS,
    T1.PROCESS,
    T1.SUBSTITUTE,
    T1.REASON,
    T2.EMPTYPE,
    T2.IS_DOCUMENT,
    T2.IS_SUBSTITUTE,
    T3.EMP_CNAME,
    T3.GENDER,
    T3.DEPARTMENT_ID,
    T1.JOBTITLE_NAME,
    T1.DEPARTMENT_NAME,
    T4.WORKING_TIME,
    T4.OFF_TIME,
    T4.LUNCH_TIME,
    (
        SELECT
            T2.DISPLAY
        FROM
            BASE.PARAM T2
        WHERE
            T2.KEY = 'process'
        AND T1.PROCESS = T2.VALUE
        AND T2.STATUS = '1') AS PROCESS_DISPLAY,
    (
        SELECT
            T2.DISPLAY
        FROM
            BASE.PARAM T2
        WHERE
            T2.KEY = 'approve_status'
        AND T1.APPROVE_STATUS = T2.VALUE
        AND T2.STATUS = '1') AS APPROVE_STATUS_DISPLAY
FROM
    HR.LEAVERECORD T1
JOIN
    BASE.LEAVETYPE T2
ON
    T1.LEAVETYPE_ID = T2.LEAVETYPE_ID
JOIN
    HR.EMPLOYEE T3
ON
    T1.EMP_ID = T3.EMP_ID
LEFT JOIN
    HR.LOCATION T4
ON
    T3.LOCATION_ID = T4.LOCATION_ID
WHERE
    T1.EMP_ID = :empId
AND T2.EMPTYPE = T3.EMPTYPE
AND T2.STATUS = '1'
ORDER BY
    T1.LEAVE_NO ASC