INSERT
INTO
    HR.LEAVERECORD
    (
        LEAVE_NO,
        EMP_ID,
        DEPARTMENT_NAME,
        JOBTITLE_NAME,
        LEAVETYPE_ID,
        REASON,
        BEGINDATE,
        BEGINHOUR,
        BEGINMIN,
        ENDDATE,
        ENDHOUR,
        ENDMIN,
        LEAVEDAYS,
        LEAVEHOURS,
        SUBSTITUTE,
        DOCUMENT,
        PROCESS,
        APPROVE_STATUS,
        CLOSE_TIME,
        CREATE_USER,
        CREATE_TIME
    )
    VALUES
    (
        :leaveNo,
        :empId,
        :departmentName,
        :jobtitleName,
        :leavetypeId,
        :reason,
        :begindate,
        :beginhour,
        :beginmin,
        :enddate,
        :endhour,
        :endmin,
        :leavedays,
        :leavehours,
        :substitute,
        :document,
        :process,
        :approveStatus,
        :closeTime,
        :createUser,
        :createTime
    )